### ISSUE TITLE
The repository lacks CI (continuous integration) testing

### ISSUE THREAD

**Issue by guicho271828** [tomsilver/pddlgym#30]
I see there are couple of scripts in pddlgym/tests, but they are not currently integrated with e.g. Travis-CI.
This makes it easier to see if a pull-request will break the tests.

**Comment by ronuchit** [comment]
Addressed in 63f7fd8684ff33f7f15873591f34b3bda093fa16 and 5fd0be2e719afeef896f4d7f503160d89529a1ca

**Comment by guicho271828** [comment]
are you running it already in Travis? Then putting the build banner in the README is nice

**Comment by ronuchit** [comment]
Addressed in 5c5a93d39e1c340ebbe3467cf0a2d0751455b5dc
