### ISSUE TITLE
Relative module reference

### ISSUE THREAD

**Issue by guicho271828** [tomsilver/pddlgym#43]
For example, in `spaces.py`,
```
from pddlgym.structs import LiteralConjunction, Literal, ground_literal
from pddlgym.parser import PDDLProblemParser
...
```
should be
```
from .structs import LiteralConjunction, Literal, ground_literal
from .parser import PDDLProblemParser
...
```

**Comment by gehring** [comment]
Do you have a motivating example for changing this? I know a commonly given reason for using relative imports is for portability's sake, but I've never really found them to be noticeably helpful. Also, I believe Google's style guide [forbids it explicitly](https://google.github.io/styleguide/pyguide.html#22-imports) (not that they get to decided how we use python, just a noteworthy example).  Personally, I'm still undecided when it comes to relative imports.

**Comment by tomsilver** [comment]
I'm going to close this for now, but we can reopen it if a motivating example / use case comes up.
