### ISSUE TITLE
Get all possible outcomes from a probabilistic effect

### ISSUE THREAD

**Issue by GCrispino** [tomsilver/pddlgym#49]
Hello!
Sorry if I am wrong, but I think that there's currently no way of getting all possible successor states by applying an action that has probabilistic effects.
The closest I found to this functionality is the PDDLEnv's method sample_transition, but it samples one of the possible outcomes. More specifically, the sampling is done in the _apply_effects method.

A way to maybe implement this functionality would be to receive a parameter in _apply_effects to get a list of possible successor states instead of sampling a single one. I'd be glad to contribute if you feel this would be useful, because I'm thinking on using PDDLGym for research on probabilistic planning, and I'd probably need this.

**Comment by ronuchit** [comment]
This sounds like a useful feature to add! It might make sense to add a new public method in the PDDLEnv class in core.py, maybe called get_all_possible_transitions(self, action) or something. In that method, we'd want to assert self.domain.is_probabilistic. This method can make use of a new flag that we add to _apply_effects, as you suggested.

Thanks for offering to contribute! Let us know if you run into any issues with the implementation, and we can help out. Please also add a test to the tests/ folder.

**Comment by GCrispino** [comment]
Awesome! Regarding the tests, would a function in test_pddlenv.py be reasonable? Also, I believe that adding a probabilistic test domain (like the test_domain) for this test would be a good idea. What do you think?

**Comment by ronuchit** [comment]
Yes, both of these sound reasonable. Please let us know if there's any issues. You can use some of the probabilistic domains in the pddl/ directory as guidance in setting up the probabilistic test domain.

**Comment by GCrispino** [comment]
All right. I'm kinda new to PDDL so I might ask for some help 😅, but I'll let you know!
