### ISSUE TITLE
InvalidAction exception can show information about actual invalid action when raised

### ISSUE THREAD

**Issue by GCrispino** [tomsilver/pddlgym#62]
There is a single occurrence of the `InvalidAction` exception on `pddlgym`s codebase.
It happens on https://github.com/tomsilver/pddlgym/blob/master/pddlgym/core.py#L82, as part of the `get_successor_state` function, when the passed action is invalid on the specific state.

I imagine it would be good and easy enough to add information on the action that's invalid on this state.

I could add a PR to this if agreed, and thought about two solutions:
1. The easiest one would be to just add a string argument when raising the exception. Something like the following:
```
raise InvalidAction(f"action {a} is invalid at the current state")
```
2. A likely cleaner solution would be to make the action `a` a parameter of the `InvalidAction` class constructor, such that the logic of printing it when the exception is raised is contained on the class definition itself.

Thoughts?

**Comment by tomsilver** [comment]
Thanks a lot for proposing this and offering to implement! I agree it would be helpful.

Between the two solutions you mention, I don't have a strong preference. Feel free to do whichever you prefer. If it were me, I would probably start with the easier one (1) and refactor if ever there is a use case that requires (2).

**Comment by GCrispino** [comment]
@tomsilver cool!

PR #63 created to address this. I went up with the simpler option after all, to make it clear that the error comes from the `get_successor_state` function in this case. Feel free to comment anything there!
