### ISSUE TITLE
How to fix the goal in slidetile

### ISSUE THREAD

**Issue by steve-z-seattle** [tomsilver/pddlgym#66]
Hi all,

I really want to fix the goal in the problem of slidetile, and set the goal *always* to be (B means blank):
1 2 3
4 5 6
7 8 B
I have not been able to figure it out. Could someone help? thanks.

Another way of getting a random problem is to start with the init state and the goal both to be show above. Then I can select random actions for `k` steps, and that would be a problem to compute on (with a sense of difficulty level), instead compute on a random problem whose difficulty level is unknown ahead of time. Thanks again.

**Comment by ronuchit** [comment]
Hi Steve,

The relevant files are as follows:
Domain description: https://github.com/tomsilver/pddlgym/blob/master/pddlgym/pddl/slidetile.pddl
Training problems: https://github.com/tomsilver/pddlgym/blob/master/pddlgym/pddl/slidetile/
Testing problems: https://github.com/tomsilver/pddlgym/blob/master/pddlgym/pddl/slidetile_test/

It seems like for this domain we only have 1 training problem (`eight01x.pddl`) and 1 testing problem (`eight02x.pddl`). So you can feel free to edit the goals in those files directly. Also, if you want, you can write a problem file generator that creates many more training and testing problems with the same goal, but different initial states! You could put such a file into https://github.com/tomsilver/pddlgym/tree/master/pddlgym/procedural_generation, and we would be happy to merge in that contribution.

Hope it helps,
Rohan

**Comment by steve-z-seattle** [comment]
I see. I will modify eight0?x.pddl directly. Thanks for the help.

**Comment by steve-z-seattle** [comment]
I see. I will modify eight0?x.pddl directly. Thanks for the help.

If I get time to work on the generation, I will let you know. A simple way of doing it is by random walk from the goal.

**Comment by steve-z-seattle** [comment]
Hi Rohan,

I was able to get what I want within 30 min (setting init state and goal both to be the one I specified above). Awesome repo by the way.

I will let you know if I can make some progress on generating games.

At this moment, you may close the issue (I am not sure if I can close it or not).

Thanks.
-Steve
