### ISSUE TITLE
Quality of Life change to auto-inject action-variables as preconditions

### ISSUE THREAD

**Issue by RushangKaria** [tomsilver/pddlgym#72]
A quality of life change would allow automatically injecting action-variables (with the same arity as the action) as preconditions into the domain schema. This is often the case when dealing with pure pddl benchmarks which do not have a low-level sim.

A parameter `auto_inject_for_pddl=True` could simply add `(stack ?x ?y)` as a precondition for an action `(stack ?x ?y)` and also add it as a corresponding predicate.

This would greatly ease adding new domain files and many benchmarks could be then be used with pddlgym out-of-box as-is.

**Comment by RushangKaria** [comment]
Does the `operators_as_actions` flag accomplish this? I am asking because it did not work correctly for me.

**Comment by tomsilver** [comment]
Thanks for opening the issue! Indeed the operators_as_actions argument is meant to serve that purpose. Can you give more info about what you tried there that didn't work?

**Comment by RushangKaria** [comment]
I tried adding a new probabilistic domain and just tried to use the domain as-is. I guess I must have made a mistake down the line somewhere. It seems to be working now (with `dynamic_action_space`).
