### ISSUE TITLE
How to get all possible actions in an environment?

### ISSUE THREAD

**Issue by koulanurag** [tomsilver/pddlgym#74]
Traditionally, `gym` supports following `env.action_space.n`. 

Though, I understand that in `pddlgym`, the number of legal action changes based on the observation. It would be still nice to get access to entire set of actions. 

Also, with each sampled action; is there a way to get discrete ( like a index) representation of the action. As of now; it returns a `Literal`. It would be nice to have some unique id associated with each index.

I intend to use your environments with a deep-learning kind of framework; so need access to `total number of actions`.

**Comment by ronuchit** [comment]
Hi there,

So, there are two complexities in PDDLGym that you don't have in regular Gym, arising from the fact that in PDDLGym, transitions are defined by operators.
(1) Actions are only defined with respect to a particular set of objects, which are fixed within an episode but may change from one episode to another. For instance, if in one episode I have objects "cup1" and "cup2", I might have actions like "Pick(cup1)" and "Pick(cup2)", but then in another episode if I have objects like "cup3" and "cup4", my actions will be different.
(2) Operators have preconditions, which means that only some actions will be possible to execute in a given state. You can see this flag `dynamic_action_space` when instantiating a PDDLGym environment object: [code](https://github.com/tomsilver/pddlgym/blob/master/pddlgym/core.py#L301).

Note that `env.action_space` is an object of type [`LiteralSpace`](https://github.com/tomsilver/pddlgym/blob/c1a0b95967221a28249accd255a7943e6664dbe6/pddlgym/spaces.py#L22).  For a particular episode, the function `env.action_space.all_ground_literals` should give you what you want.

Regarding indexing into the actions, what you can do is use `dynamic_action_space=False` when instantiating your environment, and then do something like this at the start of an episode:
```
state, _ = env.reset()
all_actions = sorted(env.action_space.all_ground_literals(state, valid_only=False))
action_ind_to_action = dict(zip(range(len(all_actions)), all_actions))
```
Here, I'm relying on sorting to give a consistent index. Note: I didn't test this code, let me know if it doesn't work.

But the issue of (1) still remains. Typically, we use graph neural network (GNN) models to be able to generalize across objects. If you want to use something simple like an MLP, you would only be able to evaluate on objects that were seen in training episodes.

**Comment by koulanurag** [comment]
Thanks for responding and sharing code snippet.
