### ISSUE TITLE
A more complex version of Sokoban ?

### ISSUE THREAD

**Issue by aymeric75** [tomsilver/pddlgym#80]
Hello,

I would like to produce a dataset for Sokoban but more complex than this one "PDDLEnvSokobanTest-v0"

By "more complex", I mean: with more tiles and maybe more boxes for the agent to move, in a word a bigger "world".

So far here is what I used (sorry, the image is small you might want to zoom in):

![init-sokoban](https://github.com/tomsilver/pddlgym/assets/12927600/e1107d66-da32-4243-ae73-60adc97eabda)

Thanks

**Comment by tomsilver** [comment]
Hi, thanks for your interest! The problem instances for `PDDLEnvSokobanTest-v0` are defined here: https://github.com/tomsilver/pddlgym/blob/master/pddlgym/pddl/sokoban_test/ It sounds like you'll want to change those instances to make them more complicated. You could do this by hand, or you could look for existing Sokoban problem instances and use those. For example, if you look at the tasks here, you'll see that they get larger as the number goes up:

https://github.com/aibasel/pyperplan/tree/master/benchmarks/sokoban

So you could potentially use those.

If you need a very large variety of tasks, you might want to use a task generator, e.g., https://github.com/AI-Planning/pddl-generators/tree/main/sokoban

Finally, you might also be interested in https://github.com/mpSchrader/gym-sokoban which doesn't use PDDL but does have a Gym interface and tasks of varying size that are randomly generated.

**Comment by aymeric75** [comment]
Thanks for your answer, but just to be sure, if I modify the task*.pddl files in sokoban_test , is it possible that the resulting visual problems will be larger in size ? (i.e. with more tiles where the agent can move).

**Comment by tomsilver** [comment]
Yes, the rendering should update automatically. But let us know if you encounter any trouble.
