### ISSUE TITLE
code not working

### ISSUE THREAD

**Issue by aymeric75** [tomsilver/pddlgym#82]
Hi,

This code:
```

import pddlgym
import imageio

env = pddlgym.make("PDDLEnvHanoi-v0")
obs, debug_info = env.reset()
img = env.render()
imageio.imsave("frame1.png", img)
for i in range(5):
    action = env.action_space.sample(obs)
    print(action)
    obs, reward, done, debug_info = env.step(action)
    img2 = env.render()
    imageio.imsave("frame"+str(i)+".png", img2)
```

only returns the exact same image

Thanks

**Comment by ronuchit** [comment]
Hi there,

There are some additional arguments you can pass into `pddlgym.make`, described here:
https://github.com/tomsilver/pddlgym/blob/master/pddlgym/core.py#L282-L304

Of these, take note of `dynamic_action_space`. The default behavior of a PDDLGym environment is that the action space contains all actions possible from _any_ state (i.e., a cross product of action predicates and object types). So, a lot of the time, when you sample an action, it will be invalid in the current state, in which case the environment no-ops. You can change this behavior by passing `dynamic_action_space=True` into `pddlgym.make`, in which case calling `env.action_space.sample` will only return actions that are valid in the current state.

By the way, if you want to make the environment crash if an invalid action is provided, feel free to also pass in `raise_error_on_invalid_action=True`. This can be great for debugging.

**Comment by aymeric75** [comment]
I used "PDDLEnvHanoi_operator_actions-v0" indeed and it works, thanks

**Comment by aymeric75** [comment]
> (You may also consider using the `hanoi_operator_actions` environment instead of `hanoi` -- see https://github.com/tomsilver/pddlgym/blob/master/pddlgym/__init__.py#L62-L65)

I sampled around 8000 steps from 4 different initial state, and I find that the number of unique actions (i.e. without the duplicates) is more than 1440, which I would have thought could not be the case for Hanoi-4-4
