### ISSUE TITLE
A bug in the step function ?

### ISSUE THREAD

**Issue by aymeric75** [tomsilver/pddlgym#87]
Hi,

When I want to sample observations from Blocks environment I noticed that, even after 1000s of samplings, the number of different observations in never above 35 or so...

Here is a code to test it:
```

import pddlgym
import numpy as np



nb_max_of_samplings = 9001

counter = 0

# a dict to show the number of occurences of each obs sampled
obs_occurences = {}

## Loading the env
env = pddlgym.make("PDDLEnvBlocks-v0", dynamic_action_space=True)



# Initializing the first State
obs, debug_info = env.reset(_problem_idx=0)

# we count the occurence of the initial obs
obs_occurences[str(obs)] = 1


while counter < nb_max_of_samplings:

    action = env.action_space.sample(obs)
    obs, reward, done, debug_info = env.step(action)

    
    if str(obs) not in obs_occurences.keys():
        obs_occurences[str(obs)] = 1
    else:
        obs_occurences[str(obs)] += 1

    print("counter: {}".format(str(counter)))

    counter += 1

print("obs_occurences")
print(obs_occurences)
print(len(obs_occurences))

```

You will notice that "print(len(obs_occurences))" always print a number below 34-35...

Yet, in Blocksworld with 3 blocks, the number of different states should be around 76 if I am correct.

Here is the pddl task that I used
```

(define (problem blocks)
    (:domain blocks)
    (:objects 
        b - block
        a - block
        c - block
        robot - robot
    )
    (:init 
        (clear c) 
        (clear a) 
        (clear b) 
        (ontable c) 
        (ontable a)
        (ontable b) 
        (handempty robot)

        ; action literals
        (pickup a)
        (putdown a)
        (unstack a)
        (stack a b)
        (stack a c)
        (pickup b)
        (putdown b)
        (unstack b)
        (stack b a)
        (stack b c)
        (pickup c)
        (putdown c)
        (unstack c)
        (stack c b)
        (stack c a)


    )
    (:goal (and (on a b) (on b a)))
)

```

(I have put a Falsy goal on purpose, but it does not change anything)

Regards

**Comment by aymeric75** [comment]
In total, there should be , i.e.:


- all blocks on table: 6 combinations
- tower of 2 blocks on each position and 1 on the robot: 3 x 6 combinations
- tower of 2 blocks on each position and the other on another position: 3 x 12
- tower of 3 blocks: 6 x 3 combinations

6+18+36+18 = 78 combinations

**Comment by ronuchit** [comment]
In your code you are starting from a fixed starting state (`env.reset(_problem_idx=0)`) and taking a long sequence of random actions from this state. Are you sure that all your 78 combinations would be reachable from this initial state? It might help to work backward: take one of the combinations you think should be occurring but that you're not seeing, and try to figure out what sequence of actions you'd expect need to be taken in order to get to that combination. Then we can try to debug why that specific sequence of actions is not occurring. Feel free to share your work here.

**Comment by aymeric75** [comment]
> In your code you are starting from a fixed starting state (`env.reset(_problem_idx=0)`) and taking a long sequence of random actions from this state. Are you sure that all your 78 combinations would be reachable from this initial state? It might help to work backward: take one of the combinations you think should be occurring but that you're not seeing, and try to figure out what sequence of actions you'd expect need to be taken in order to get to that combination. Then we can try to debug why that specific sequence of actions is not occurring. Feel free to share your work here.

I created a Pull request that I think can be relevant, indeed, there is no reason to not have the "piles" returned by the get_objects_from_obs function to be shuffled, this way it's closer to the arbitrary nature of the location of the blocks (or towers of blocks) on the table. It also greatly help for generating a more representative dataset
