### ISSUE TITLE
Blocksworld: order of init predicates has no influence ?

### ISSUE THREAD

**Issue by aymeric75** [tomsilver/pddlgym#88]
With this code:
```

## Loading the env
env = pddlgym.make("PDDLEnvBlocks-v0", dynamic_action_space=True)
# Initializing the first State
obs, debug_info = env.reset(_problem_idx=0)
img, blocks_data = env.render()
img = img[:,:,:3]
plt.imsave("img_0.png", img)
plt.close()

```

If I use two slightly different versions of the same problem pddl:
```

(define (problem blocks)
    (:domain blocks)
    (:objects 
        b - block
        a - block
        c - block
        robot - robot
    )
    (:init 
        (clear c) 
        (clear a) 
        (clear b) 
        (ontable c) 
        (ontable a)
        (ontable b) 
        (handempty robot)

        ; action literals
        (pickup a)
        (putdown a)
        (unstack a)
        (stack a b)
        (stack a c)
        (pickup b)
        (putdown b)
        (unstack b)
        (stack b a)
        (stack b c)
        (pickup c)
        (putdown c)
        (unstack c)
        (stack c b)
        (stack c a)

    )
    (:goal (and (on a b) (on b a)))
)
```

and another version where I just switch the predicates in the init part, like so:
```     
        (clear a) 
        (clear c) 
        (clear b)      
        (ontable a)
       (ontable c) 
        (ontable b) 
```

It return exacltly the same image:
![img_0](https://github.com/tomsilver/pddlgym/assets/12927600/0bd9bef5-6e8c-460a-a4f8-5d780c6e8c0d)

i.e. the blocks are in the same order... why ?

**Comment by ronuchit** [comment]
The set of initial predicates, `(:init ... )` is an _unordered set_ defining the initial state.  Switching around the predicates in that set is not expected to make any difference.

**Comment by aymeric75** [comment]
> The set of initial predicates, `(:init ... )` is an _unordered set_ defining the initial state. Switching around the predicates in that set is not expected to make any difference.

so if I understand, the action putdown(a) can indiferentiably put the block a on any free spot on the table and this will result in the same state (but not the same image)

**Comment by aymeric75** [comment]
I just need to be able to make the difference, in my code, between two observations that are visually different

**Comment by aymeric75** [comment]
> I just need to be able to make the difference, in my code, between two observations that are visually different

[EDIT] actually, I now return the tuple  (piles, holding) from the render() function, that should allow me to have obs that are also visually different

**Comment by ronuchit** [comment]
yes, you'll need to modify the render() function for this
