### ISSUE TITLE
How to associate a pddlgym env to another problem folder than default ?

### ISSUE THREAD

**Issue by aymeric75** [tomsilver/pddlgym#92]
Hello,

If I call

`env = pddlgym.make("PDDLEnvHanoi-v0", dynamic_action_space=True)`

and then

`env.reset(_problem_idx=0)`

the reset function will use a problem stored in pddlgym/pddlgym/pddl/hanoi folder.

I have different sorts of hanoi problems that I would like to put in different folders like: hanoi-3-9, hanoi-4-4 etc

Is there a way to call for these specific folders in the code ? 

Thanks

**Comment by ronuchit** [comment]
unfortunately it's not supported out of the box -- sorry :( 
in your personal fork of pddlgym, you could change the logic here to support what you want to do: https://github.com/tomsilver/pddlgym/blob/master/pddlgym/__init__.py#L21-L29

closing now but feel free to re-open if issues persist

**Comment by aymeric75** [comment]
thanks!
