### ISSUE TITLE
Is this a legal Sokoban transition ?

### ISSUE THREAD

**Issue by aymeric75** [tomsilver/pddlgym#93]
Hello,

I want to list all the possible transitions in Sokoban (with 9 free spaces, 1 agent and 1 boxe, and 1 fixed goal location).

In my listing I have this transition:

![Soko-transi16](https://github.com/tomsilver/pddlgym/assets/12927600/f34e0f0e-2177-4b84-9c89-3084b82cf8cf)

Is it a legal transition ? (my guess is that it is not, since the agent is ON the box on the 2nd state)

Same question for this transition:

![Soko-transi17](https://github.com/tomsilver/pddlgym/assets/12927600/b204f1c2-35c4-4a5c-8de3-a742c4c5dd94)

(here, since the goal is already solved, the agent should not be allow to move, no ?)

Regards

**Comment by ronuchit** [comment]
The first one looks illegal to me, yeah. For the second one, generally in Gym and PDDLGym, the goal being solved is handled by the `done` flag returned by `env.step()`, and there is undefined behavior if you try to take any more steps in the environment after that. Once you receive `done = True` from an `env.step()` call (https://github.com/tomsilver/pddlgym/blob/master/pddlgym/core.py#L491), you should move onto the next episode by calling `env.reset()`.
