### ISSUE TITLE
AttributeError: 'ForAll' object has no attribute 'predicate' in 'def ground_literal(lifted_lit, assignments):'

### ISSUE THREAD

**Issue by wNighthowler** [tomsilver/pddlgym#94]
I find that there is something wrong with the fuction 'ground_literal(lifted_lit, assignments)'.
When I use my own domain with 'forall', I noticed that you have considered 'ForALL' and 'Exist'. 
But in 'ground_literal(lifted_lit, assignments)', it just return lifted_lit.predicate(*ground_vars), without considering the 'body' of 'ForALL‘ which has no 'predicate'.
I'm wondering if you intend to refine this part of the pddl syntax analysis so that it supports the 'forall' syntax. 
Thank you

**Comment by tomsilver** [comment]
Hi, thanks for the issue! You are right that `ground_literal` won't work with `ForAll` or `Exists`. The way that we currently handle quantifiers is through prolog (https://github.com/tomsilver/pddlgym/blob/master/pddlgym/prolog_interface.py). The function docstring does indicate that only `Literal` instances are supported.

**Comment by wNighthowler** [comment]
Have you solved this yet please, I've looked at the parser code a little bit and it's a lot of work!
I changed the prolog mode in the code and it does work, but with the forall syntax (forall is in the effect) it looks like it still gets stuck on struct.py lifted_lit.predicate(*ground_vars).

**Comment by tomsilver** [comment]
Sorry, I may have misunderstood your original message. Are you saying that you are trying to add a new PDDL domain? Can you share code to reproduce the issue that you're encountering?

**Comment by wNighthowler** [comment]
Yes, I have solved it by changing my PDDL domain details recently, without using 'ForAll'. 
Here is the origin PDDL domain code with 'ForAll', which is a simple test, but doesn't work in ground_literal(lifted_lit, assignments).
I don't know if it is a problem about the pddlgym Version or something else.

(define (domain robotics)
  (:requirements :strips :typing)

  (:types
    obs region door
  )

  (:predicates
    (RobLoc ?loc - region)
    (RobNearDoor ?door - door)
    (RobNearObs ?obs - obs)
    (ObsLoc ?obs - obs ?loc - region)
    (NextTo ?region1 - region ?door - door ?region2 - region)
    (Open ?door - door)
    (Close ?door - door)
    (loadAready ?obs - obs)
    (HandEmpty)
  )

  (:action GotoObs
    :parameters (?obs - obs ?region - region)
    :precondition (and (RobLoc ?region) (ObsLoc ?obs ?region))
    :effect (and (RobNearObs ?obs))
  )

  (:action GotoDoor
    :parameters (?door - door ?region1 - region ?region2 - region)
    :precondition (and (RobLoc ?region1) (NextTo ?region1 ?door ?region2))
    :effect (and (RobNearDoor ?door))
  )

  (:action OpenDoor
    :parameters (?door - door ?region1 - region ?region2 - region)
    :precondition (and (RobNearDoor ?door) (Close ?door) (NextTo ?region1 ?door ?region2))
    :effect (and (Open ?door)
                 (not (Close ?door)))
  )

  (:action Load
    :parameters (?obs - obs)
    :precondition (and (RobNearObs ?obs) (HandEmpty))
    :effect (and (loadAready ?obs)
                 (not (HandEmpty))
                 (forall (?region - region) (not (ObsLoc ?obs ?region))))
  )

  (:action UnLoad
    :parameters (?obs - obs ?region - region)
    :precondition (and (loadAready ?obs) (RobLoc ?region) (not (HandEmpty)))
    :effect (and (ObsLoc ?obs ?region)
                 (HandEmpty)
                 (not (loadAready ?obs)))
  )

  (:action Cross
    :parameters (?region1 - region ?door - door ?region2 - region)
    :precondition (and (Open ?door) (NextTo ?region1 ?door ?region2) (RobLoc ?region1))
    :effect (and (RobLoc ?region2)
                 (not (RobLoc ?region1))
                 (forall (?door - door) (not (RobNearDoor ?door)))
                 (forall (?obs - obs) (not (RobNearObs ?obs))))
  )
)
